image: node:latest

stages:
  - dependencies
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: dependencies
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build